### ISSUE TITLE
CCDR tools into RDL tools

### ISSUE THREAD

**Issue by matamadio** [GFDRR/CCDR-tools#33]
# Objective
Take the existing CCDR tools and make them:
- Easier to use
- More efficient
- Flexible, that can be linked to different datasets provided by RDL

![immagine](https://github.com/user-attachments/assets/5d4200b6-d24c-48f1-a518-a19d690e5d59)

# Workplan and Timeline
Mat and Jasper to split tasks and coordinate releases on new branch [dev_push](https://github.com/GFDRR/CCDR-tools/tree/dev_push).
First we optimise and test a flood-only version, which is richer in terms of options compared to other hazards.
Once solid and tested, we try to split the components that can be used for multi-hazard from hazard-specific configuration.
Then we produce a launcher that can:
1) wrap everything in a visual interface and guide the user in a friendly way (limit manual data preparation, avoid script editing)
2) execute the program in batch (sequential for different parameters)
3) produce maps and charts once results are calculated

# Tasks
- #32
- #6 (1/3)
- [x] Ensure that parallel processing works when running program from jupyter notebook
- #34 
- [x] Add flood damage functions for all regions
- [x] Re-structure code as common parts and hazard-specific interfaces
  - #35
  - [x] Efficiency: don't download datasets that have been previously downloaded
- [x] Update documentation to reflect changes
- [ ] <s>Chance to concatenate (batch) several analyses, e.g. several countries one after the other.</s>
- [x] Extended testing, find the cap limitations

# Timeline

**Comment by matamadio** [comment]
# Tasks update

### GUI
- [x] New GUI for selecting hazard, and then for running the specific hazard screening. Only flood is included for now, placeholder for cyclones and heat stress.
  - Move away from [old hazard notebooks](https://github.com/GFDRR/CCDR-tools/tree/dev_push/tools/notebooks/old) (those feature superseeded analysis code) and focus on the new approach (dynamic GUI): different versions of the same GUI are generated dynamically based on each hazard's `hzd_config.py` file
  - For now, the choice leads to hazard-specific GUI static notebooks - let's finalise floods first, then extend to other hazards using config files approach.

### FUNCTIONALITIES
- [x] **Country selector**: dropdown menu with all country names as autocomplete field; resolve argument as ISO_A3 (based on either a csv with global [name, ISO_A3, WB_REGION]
- [x] Connect `GUI.py` to `run_analysis.py` (_run analysis_ button simply runs `try.py` at the moment). Rename `try.py` into `manual_run.py`, used just for testing purpose, might delete later.
  - [x] Ensure parallel processing works as expected, and all stages of progress from run_analytics are printed in the interface
- [x] Auto-fetching and processing of ADM, POP. BU.
  - [ ] AGR will need pre-clipped input data on S3 - original source data too big to fetch and process. 
- [x] Preview impact functions for each exp based on country georegion.
- [x] Save output as multi-tab excel with auto-summary, and multi-layer geopackage.
- [x] Preview results as map and [EAI charts](https://github.com/GFDRR/CCDR-tools/tree/dev_push/tools/notebooks/UI/plot_EAI) after analysis is completed

### Splitting functions
- [x] `input_utils.py` includes libs to fetch and pre-process input data. Only called if input_data not already present in the folder.
- [x] Integrate ALL processing from `fetch_WSF19.ipynb` into `input_utils.py` and `run_analysis.py` as default option when "Built-up" exposure is selected, no custom dataset is specified, and _ISO_BU.tif_ is not already present in data folder.
  - [ ] tile-merging of Fathom data (usually done separately beforehand, could easily be part of the one-click process).
  2. `run_analysis.py` when input data are in place, produces results

### Misc issues:

- [x] **GH repo**: set protection rules for push to main (dev_push has none)
- [x] dev_push branch: file renaming and restructuring folders.

**Comment by matamadio** [comment]
All items have been completed with next PR merge. Issue closed.
